name: WordPress CI/CD

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Set up WordPress
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
    - name: Install dependencies
      run: composer install
    - name: WordPress setup
      run: |
        wp core download
        wp config create --dbname=wordpress --dbuser=root --dbpass=password --dbhost=localhost
        wp core install --url="http://localhost:8080" --title="My WordPress Site" --admin_user="admin" --admin_password="password" --admin_email="admin@example.com"
    - name: Build Docker image
      run: docker build -t vikas369/mydocker-7:wordpress-latest ./wordpress
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Push Docker image
      run: docker push vikas369/mydocker-7:wordpress-latest

- run: composer require --dev squizlabs/php_codesniffer
- run: vendor/bin/phpcs --standard=WordPress .

