name: Go Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./go-app
          push: true
          tags: v1

      - name: SSH into staging server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop myapp_go-app || true
            docker rm myapp_go-app || true
            docker pull vikas369/myapp_go-app:v1
            docker run -d --name myapp_go-app -p 8080:8080 vikas369/myapp_go-app:v1

